global:
templates:
- '/etc/alertmanager/*.tmpl'
route:
  receiver: page
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 1m
  
  routes:
      - match:
          severity: smoketest
        receiver: robotics
        repeat_interval: 1m
      - match:
          severity: ready
        receiver: ready
        repeat_interval: 1m
      - match:
          severity: triage
          app: yourAppName
        receiver: yourAppTeam_Dev
        routes:
        - match:
            env: MyEnvName
          receiver: yourAppTeam_MyEnv_Team
        - match:
            env: yourEnvName
          receiver: yourAppTeam_YourEnv_Team
      - match:
          severity: triage
          app: myAppName
        receiver: myAppTeam_Dev
        routes:
        - match:
            env: MyEnvName
          receiver: myAppTeam_MyEnv_Team
        - match:
            env: yourEnvName
          receiver: myAppTeam_YourEnv_Team
 

receivers:
- name: page
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/page
  - url: http://192.168.10.142:5000/alert/roboticsPAGE

- name: ready
  webhook_configs:
  - url: http://tsm-robotics-web:5000/notify/ready_to_use

- name: robotics
  webhook_configs:
  - url: http://192.168.10.142:5000/notify/roboticsSmokeTest

- name: yourAppTeam_Dev
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_Dev
  - url: http://192.168.10.142:5000/alert/roboticsAlert

- name: yourAppTeam_MyEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_MyEnv_Team
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_Dev
  - url: http://192.168.10.142:5000/alert/roboticsAlert1
  
- name: yourAppTeam_YourEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_YourEnv_Team
  - url: http://192.168.10.142:5000/alert/roboticsAlert2

- name: myAppTeam_Dev
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/myAppTeam_Dev
  - url: http://192.168.10.142:5000/alert/roboticsAlert3

- name: myAppTeam_MyEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/myAppTeam_MyEnv_Team
  - url: http://tsm-robotics-web:5000/alert/myAppTeam_Dev
  - url: http://192.168.10.142:5000/alert/roboticsAlert4
  
- name: myAppTeam_YourEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/myAppTeam_YourEnv_Team
  - url: http://192.168.10.142:5000/alert/roboticsAlert5
