global:
templates:
- '/etc/alertmanager/*.tmpl'
route:
  receiver: page
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 1m
  
  routes:
      - match:
          severity: smoketest
        receiver: robotics
      - match:
          severity: triage
        receiver: yourAppTeam_MyEnv_Dev
        routes:
        - match:
            app: "yourAppName"
            env: "MyEnvName"
          receiver: yourAppTeam_MyEnv_Team
        - match:
            app: "yourAppName"
            env: "MyEnvName"
          receiver: yourAppTeam_YourEnv_Team
 

receivers:
- name: page
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/page

- name: robotics
  webhook_configs:
  - url: http://tsm-robotics-web:5000/notify/robotics

- name: yourAppTeam_Dev
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_Dev
  - url: http://tsm-robotics-web:5000/alert/robotics
  

- name: yourAppTeam_MyEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_MyEnv_Team
  - url: http://tsm-robotics-web:5000/alert/robotics
  
- name: yourAppTeam_YourEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_YourEnv_Team
  - url: http://tsm-robotics-web:5000/alert/robotics
