global:
templates:
- '/etc/alertmanager/*.tmpl'
route:
  receiver: robotics
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 30m
  routes:
    - receiver: triage
      match:
        severity: triage
      group_wait: 10s
      repeat_interval: 1m
      continue: true
    - receiver: smoketest
      match:
        severity: smoketest
      group_wait: 10s
      continue: true

receivers:
- name: robotics
  webhook_configs:
  - url: http://192.168.10.142:5000/alert/robotics
- name: triage
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/triage
- name: smoketest
  webhook_configs:
  - url: http://tsm-robotics-web:5000/notify/smoketest
