global:
templates:
- '/etc/alertmanager/*.tmpl'
route:
  receiver: page
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 30m
  routes:
    - receiver: triage
      match:
        severity: triage
      group_wait: 10s
      repeat_interval: 1m
    - receiver: smoketest
      match:
        severity: smoketest
      group_wait: 10s

receivers:
- name: page
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/page
- name: triage
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/triage
- name: smoketest
  webhook_configs:
  - url: http://tsm-robotics-web:5000/notify/smoketest
