global:
templates:
- '/etc/alertmanager/*.tmpl'
route:
  receiver: page
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 1m
  
  routes:
    - match:
        app: "yourAppName"
      receiver: yourAppTeam_Dev
      group_wait: 10s
      repeat_interval: 1m
      routes:
      - match:
          severity: triage
          env: "MyEnvName"
        receiver: yourAppTeam_MyEnv_Team
      - match:
          severity: triage
          env: "yourEnvName"
        receiver: yourAppTeam_YourEnv_Team
      - match:
          severity: smoketest
        receiver: robotics

receivers:
- name: page
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/page

- name: robotics
  webhook_configs:
  - url: http://tsm-robotics-web:5000/notify/robotics

- name: yourAppTeam_Dev
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_Dev
  - url: http://tsm-robotics-web:5000/alert/robotics
  

- name: yourAppTeam_MyEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_MyEnv_Team
  - url: http://tsm-robotics-web:5000/alert/robotics
  
- name: yourAppTeam_YourEnv_Team
  webhook_configs:
  - url: http://tsm-robotics-web:5000/alert/yourAppTeam_YourEnv_Team
  - url: http://tsm-robotics-web:5000/alert/robotics
