  
groups:
- name: MyAppConfigCheck
  rules:
  - record: app:perc_readiness
    expr: sum(configcheck) by (app, env) /  count(configcheck) by (app, env)    

  - alert: AutomatedConfigCheck
    expr: configcheck == 0
    for: 1m
    labels:
      severity: triage
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Configuration Mismatch ==>  Application: {{ $labels.app }} Environment: {{ $labels.env }} Value: {{ $labels.path }} ."  

  - alert: ReadyToVerify
    expr: app:perc_readiness == 1
    for: 1m
    labels:
      severity: smoketest
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment Ready for Smoke Testing.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
  
  - alert: ReadyToUse
    expr: app:perc_readiness == 1
    for: 1m
    labels:
      severity: ready
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment Ready for LIVE use.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
  
