  
groups:
- name: TouchlessConfigCheck
  rules:
  - record: app:ready_to_test
    expr: sum(configcheck) by (app, env) / count(configcheck) by (app, env)
    
  - record: app:ready_to_use
    expr: readiness_test{success="True"} != -1

  - alert: AutomatedConfigCheck
    expr: configcheck == 0
    for: 10s
    labels:
      severity: triage
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Configuration Mismatch ==>  Application: {{ $labels.app }} Environment: {{ $labels.env }} Value: {{ $labels.path }} ."  

  - alert: ReadyToVerify
    expr: app:ready_to_test == 1 unless (app:ready_to_use)
    for: 1m
    labels:
      severity: ready_to_test
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment Ready for Smoke Testing.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
      isready: "True"
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"

  - alert: EnvChanging
    expr: app:ready_to_test != 1
    for: 10s
    labels:
      severity: not_ready
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment has been modified.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
      isready: "False"
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    
  - alert: ReadyToUse
    expr: app:ready_to_use > 0 
    for: 1m
    labels:
      severity: ready_to_use
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment Ready for LIVE use.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
      isready: "Live"
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
  
