  
groups:
- name: MyAppConfigCheck
  rules:
  - record: MyAppConfigValue:S1:Market
    expr: absent( aut_config_info {envname="S1", YV="NYC"} )*2 or aut_config_info{envname="S1", YV="NYC"}
    
  - record: MyAppConfigValue:S2:Market
    expr: absent( aut_config_info {envname="S1", YV="DLS"} )*2 or aut_config_info{envname="S1", YV="DLS"}
    
  - alert: MyAppConfigInvalid
    expr: MyAppConfigValue:S1:Market == 2
    for: 1m
    labels:
      severity: triage
    annotations:
      description: "MyApp:S1:Market is NOT NYC"  
      
  - alert: MyAppConfigInvalid2
    expr: MyAppConfigValue:S2:Market == 2
    for: 1m
    labels:
      severity: triage
    annotations:
      description: "MyApp:S2:Market is NOT DLS"  
