  
groups:
- name: MyAppConfigCheck
  rules:
  - record: app:perc_readiness
    expr: sum(configcheck) by (app, env) /  count(configcheck) by (app, env)    
    
  - record: app:ready_to_test
    expr: (sum(configcheck) by (app, env) /  count(configcheck) by (app, env)) == 1
    
  - record: app:ready_to_use
    expr: ceil(predict_linear(app:ready_to_test[24h], 30))

  - alert: AutomatedConfigCheck
    expr: configcheck == 0
    for: 1m
    labels:
      severity: triage
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Configuration Mismatch ==>  Application: {{ $labels.app }} Environment: {{ $labels.env }} Value: {{ $labels.path }} ."  

  - alert: ReadyToVerify
    expr: app:ready_to_test == 1
    for: 1m
    labels:
      severity: smoketest
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment Ready for Smoke Testing.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
  
  - alert: ReadyToUse
    expr: app:ready_to_use == 1
    for: 1m
    labels:
      severity: ready
      app: "{{ $labels.app }}"
      env: "{{ $labels.env }}"
    annotations:
      description: "Environment Ready for LIVE use.  Application: {{ $labels.app }} Environment: {{ $labels.env }}."  
  
